// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pNQ3qJFS1TWHqdfJbfomIYkq_5sE_Bc',
    appId: '1:961608516651:web:831d71cd400ac26354566e',
    messagingSenderId: '961608516651',
    projectId: 'lecturerfinder',
    authDomain: 'lecturerfinder.firebaseapp.com',
    storageBucket: 'lecturerfinder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpkjlHmQOEE8K7oD0RBSBFQHNdX4Hu1I',
    appId: '1:961608516651:android:caa463782e7a895054566e',
    messagingSenderId: '961608516651',
    projectId: 'lecturerfinder',
    storageBucket: 'lecturerfinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJR7Rri7o-8_Rrhq6BSdPoegKnpMMFaU',
    appId: '1:961608516651:ios:58a77afbe410bce754566e',
    messagingSenderId: '961608516651',
    projectId: 'lecturerfinder',
    storageBucket: 'lecturerfinder.firebasestorage.app',
    iosBundleId: 'com.example.lecturerFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVJR7Rri7o-8_Rrhq6BSdPoegKnpMMFaU',
    appId: '1:961608516651:ios:58a77afbe410bce754566e',
    messagingSenderId: '961608516651',
    projectId: 'lecturerfinder',
    storageBucket: 'lecturerfinder.firebasestorage.app',
    iosBundleId: 'com.example.lecturerFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5pNQ3qJFS1TWHqdfJbfomIYkq_5sE_Bc',
    appId: '1:961608516651:web:6ff478393539b6a354566e',
    messagingSenderId: '961608516651',
    projectId: 'lecturerfinder',
    authDomain: 'lecturerfinder.firebaseapp.com',
    storageBucket: 'lecturerfinder.firebasestorage.app',
  );
}
